name: Build & Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            backend/
            backend/captain-definition
          outPath: deploy.tar

      - uses: caprover/deploy-from-github@main
        with:
          server: '${{ secrets.CAPROVER_SERVER_BACKEND_STAGIN }}'
          app: '${{ secrets.APP_NAME_BACKEND_STAGING }}'
          token: '${{ secrets.APP_TOKEN_BACKEND_STAGING }}'
